gravitee-io/gravitee-gateway-api

src/main/java/io/gravitee/gateway/api/stream/WriteStream.java
To support back-pressure, write stream must be queryable about their queue size. Also, we need to register a handler to know when they are able to receive buffers again, the drain handler.
=> Added back pressure to WriteStream

src/main/java/io/gravitee/gateway/api/Response.java, src/main/java/io/gravitee/gateway/api/proxy/ProxyResponse.java
Closes gravitee-io/issues#2381
=> fix(http): Keep the status message as part of the response for consumer

src/main/java/io/gravitee/gateway/api/Request.java, src/main/java/io/gravitee/gateway/api/RequestWrapper.java, src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java, src/main/java/io/gravitee/gateway/api/el/EvaluableResponse.java
* Add Path Parameters in execution context, so they can be used in EL engine
* Move `EvaluableRequest` and `EvaluableResponse` to gateway-api repo, to be shared with policies
Closes gravitee-io/issues#4431
=> feat(processor): add path parameters processing

src/main/java/io/gravitee/gateway/api/Response.java
Closes gravitee-io/issues#6205
=> fix: add end handler to allow processor execution after request ends

pom.xml, src/main/java/io/gravitee/gateway/api/http/HttpHeaders.java, src/test/java/io/gravitee/gateway/api/el/EvaluableExtractorTest.java, src/test/java/io/gravitee/gateway/api/el/EvaluableSSLSessionTest.java, src/test/java/io/gravitee/gateway/api/http/HttpHeadersTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/6946
Add `deeplyEquals` method on HttpHeaders to be able to have deep equality on this object.
=> feat: add deeplyEquals method for HttpHeaders

src/main/java/io/gravitee/gateway/api/Request.java, src/main/java/io/gravitee/gateway/api/RequestWrapper.java, src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java, src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java, src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java, src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequestImpl.java
This handler allows to react upon client closing a connection.
This is useful when e.g. a SSE client calls `EventSource.close` to propagate
this event to the upstream service
see https://github.com/gravitee-io/issues/issues/7093
see https://github.com/gravitee-io/gravitee-api-management/pull/1653
---
- use it directly by updating your project with version: `1.27.4-feat-request-close-handler-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.27.4-feat-request-close-handler-SNAPSHOT/gravitee-gateway-api-1.27.4-feat-request-close-handler-SNAP …
=> fix: add a close handler on the request interface

src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
Remove interrupted field and method from context because unused anymore.
---
- use it directly by updating your project with version: `1.33.0-prototype-reactive-interuption-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.33.0-prototype-reactive-interuption-SNAPSHOT/gravitee-gateway-api-1.33.0-prototype-reactive-interuption-SNAPSHOT.zip)
=> fix(jupiter): remove isInterrupted method from ctx

pom.xml, src/main/java/io/gravitee/gateway/reactive/api/ExecutionFailure.java, src/main/java/io/gravitee/gateway/reactive/api/policy/Policy.java, src/main/java/io/gravitee/gateway/reactive/api/policy/SecurityPolicy.java
Add `SecurityPolicy` interface
---
- use it directly by updating your project with version: `1.33.0-prototype-reactive-security-chain-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.33.0-prototype-reactive-security-chain-SNAPSHOT/gravitee-gateway-api-1.33.0-prototype-reactive-security-chain-SNAPSHOT.zip)
=> feat(jupiter): add SecurityPolicy

src/main/java/io/gravitee/gateway/api/http/DefaultHttpHeaders.java, src/main/java/io/gravitee/gateway/api/http/HttpHeaders.java, src/test/java/io/gravitee/gateway/api/http/DefaultHttpHeadersTest.java, src/test/java/io/gravitee/gateway/api/http/HttpHeadersTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7812
3.15 introduced a refactoring of the HTTP Headers used in the Gateway. It does not rely on gravitee-common `HTTPHeaders` anymore but on gateway-api HTTPHeaders.
This new version is used as an `Iterable<Map.Entry<String, String>>`, breaking the contract for users using `MultiValueMap<String, String>` methods, or multi value capabilities.
To not break this new contract and open the possibilities too wildly to the policies relying on it, `MultiValueMap` is implemented at implementation level, to keep the "old behavior" only internally
---
- use it directly by updating your project …
=> fix: restore HTTP headers backward compatibility

pom.xml, src/main/java/io/gravitee/gateway/api/service/ApiKey.java, src/main/java/io/gravitee/gateway/api/service/ApiKeyService.java, src/main/java/io/gravitee/gateway/api/service/Subscription.java, src/main/java/io/gravitee/gateway/api/service/SubscriptionService.java, src/test/java/io/gravitee/gateway/api/service/SubscriptionTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7360
This adds services to manage subscriptions and api keys.
Policies should never access to underlying repository directly,
So they will use those cache managers instead of repositoryWrappers.
---
- use it directly by updating your project with version: `1.36.0-refactor-apiKeysAndSubsManagers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.36.0-refactor-apiKeysAndSubsManagers-SNAPSHOT/gravitee-gateway-api-1.36.0-refactor-apiKeysAndSubsManagers-SNAPSHOT.zip)
=> feat: add managers for api key and subscription caches

CHANGELOG.md, src/main/java/io/gravitee/gateway/api/http/DefaultHttpHeaders.java, src/main/java/io/gravitee/gateway/api/http/HttpHeaders.java, src/test/java/io/gravitee/gateway/api/http/DefaultHttpHeadersTest.java, src/test/java/io/gravitee/gateway/api/http/HttpHeadersTest.java
**Issue**
NA
As https://github.com/gravitee-io/gravitee-gateway-api/pull/119/files#diff-63278a0037ab944b4f7d466c0ed4c3bc4db8564949dda3aa092368ff7a3bd062R33 introduced some breaking changes between `1.34` and `1.35` we aren't able to use the latest `1.36.1` into `APIM 3.18.0`. 
So I created a `1.34.x` branch and merge `1.32.x` which contains a fix on the headers.
=> Merge `1.32.x` into `1.34.x`

src/main/java/io/gravitee/gateway/jupiter/api/context/Request.java
This adds the support of websocket as we know it in the current v3
---
- use it directly by updating your project with version: `1.37.0-jupiter-websocket-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.37.0-jupiter-websocket-support-SNAPSHOT/gravitee-gateway-api-1.37.0-jupiter-websocket-support-SNAPSHOT.zip)
=> feat(jupiter): add websocket support

src/main/java/io/gravitee/gateway/api/http/DefaultHttpHeaders.java, src/test/java/io/gravitee/gateway/api/http/DefaultHttpHeadersTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7812
https://github.com/gravitee-io/issues/issues/8153
Return null instead of an empty list when getting an undefined header.
Returning an empty list is causing the following EL to be evaluated to `true`:
`{#request.headers['X-Gravitee-No-Present'] != null}`
---
- use it directly by updating your project with version: `1.32.4-7812-fix-get-value-without-the-header-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.32.4-7812-fix-get-value-without-the-header-SNAPSHOT/gravi …
=> fix: return null instead of empty list when getting an undefined header

src/main/java/io/gravitee/gateway/jupiter/api/context/Request.java, src/main/java/io/gravitee/gateway/jupiter/api/context/Response.java
**Issue**
gravitee-io/issues#8030
While working on the issue I wanted to add some javadoc details to better explain how request / response body or chunks can be consumed. I found that the `onChunk(...)` method wasn't well name and renamed it to` onChunks(...)` (with an 's' to be aligned with the wording). 
This can be considered as a breaking change but it is measured because Jupiter is still in its **alpha** version and, currently, only few policies have been migrated and they are not relying on the `onChunks(...)` method. We can consider it safe to make this change without taking care of the backward compatibility for now.
=> fix: properly name onChunks method

src/main/java/io/gravitee/gateway/api/service/SubscriptionService.java
**Issue**
https://github.com/gravitee-io/issues/issues/8232
fix: SubscriptionService searches a subscription from a given API, client_id, and plan
In 3.19, we replaced the SubscriptionRepositoryWrapper by a SubscriptionService, handling subscriptions.
This introduced a regression :
API and client_id wasn't an enough precise criteria to precisely find a subscription : this fixes adds the plan criteria.
---
- use it directly by updating your project with version: `1.37.3-fix-fixSubscriptionCache-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gr …
=> fix: SubscriptionService searches a subscription from a given API, client_id, and plan

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/context/MessageRequest.java
**Issue**
https://github.com/gravitee-io/issues/issues/8036
Adding a body method to the `MessageRequest` so we can access to the body content of an incoming request
---
- use it directly by updating your project with version: `1.41.0-8036-http-post-entrypoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.41.0-8036-http-post-entrypoint-SNAPSHOT/gravitee-gateway-api-1.41.0-8036-http-post-entrypoint-SNAPSHOT.zip)
=> feat(message): access body from MessageRequest

src/main/java/io/gravitee/gateway/jupiter/api/context/HttpRequest.java, src/main/java/io/gravitee/gateway/jupiter/api/context/MessageRequest.java
**Issue**
https://github.com/gravitee-io/issues/issues/8036
Fix the previous commit by moving `body()` from `MessageRequest` to `HttpRequest`
---
- use it directly by updating your project with version: `1.41.1-8036-http-post-entrypoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.41.1-8036-http-post-entrypoint-SNAPSHOT/gravitee-gateway-api-1.41.1-8036-http-post-entrypoint-SNAPSHOT.zip)
=> fix(request): move body() from Message to Http

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
**Issue**
https://github.com/gravitee-io/issues/issues/8245
https://github.com/gravitee-io/issues/issues/8247
Implement basic kafka endpoint for both subscribe and publish mode
---
- use it directly by updating your project with version: `1.42.0-8245-kafka-consumers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.42.0-8245-kafka-consumers-SNAPSHOT/gravitee-gateway-api-1.42.0-8245-kafka-consumers-SNAPSHOT.zip)
=> feat(kafka): add kafka endpoint

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/context/HttpRequest.java, src/main/java/io/gravitee/gateway/jupiter/api/ws/WebSocket.java
**Issue**
https://github.com/gravitee-io/issues/issues/8253
Introduce a dedicated WebSocket interface for the new Jupiter engine that allows to directly deal with reactive.
=> feat: add dedicated WebSocket interface for jupiter

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/ExecutionFailure.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/EntrypointConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/context/GenericExecutionContext.java, src/main/java/io/gravitee/gateway/jupiter/api/context/HttpExecutionContext.java, src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java, src/main/java/io/gravitee/gateway/jupiter/api/context/MessageExecutionContext.java, src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java, src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java
**Issue**
https://github.com/gravitee-io/issues/issues/8361
Properly manage error on async api reactor.
---
- use it directly by updating your project with version: `1.48.0-8361-error-handling-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-8361-error-handling-SNAPSHOT/gravitee-gateway-api-1.48.0-8361-error-handling-SNAPSHOT.zip)
=> feat(): add processor and error on async api

src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
**Issue**
https://github.com/gravitee-io/issues/issues/8498
Extracted from [gravitee-io/gravitee-api-management@`1b27371` (#2510)](https://github.com/gravitee-io/gravitee-api-management/pull/2510/commits/1b273719679b0a1da3a540619767eeac6c001222#diff-4d5a2181d283c81b5b089db4714dd97b4608a4f2ba81e4b61ada8358c1c13440R55)
Add ATTR_INTERNAL_SECURITY_TOKEN constant to handle apikey vs keyless plans selection
---
- use it directly by updating your project with version: `1.44.1-8498-jupiter-apikey-fallback-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gatewa …
=> Add ATTR_INTERNAL_SECURITY_TOKEN constant

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/connector/Connector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-92
Implement common way send stop hook to entrypoint connectors.
---
- use it directly by updating your project with version: `1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT/gravitee-gateway-api-1.48.0-apim-92-entrypoint-lifecycle-stop-SNAPSHOT.zip)
=> feat: handle stop on entrypoint connector

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/context/HttpExecutionContext.java, src/main/java/io/gravitee/gateway/jupiter/api/context/MessageExecutionContext.java
https://graviteecommunity.atlassian.net/browse/APIM-98
Add method to easily interrupt body or message flow
---
- use it directly by updating your project with version: `1.48.0-apim-98-better-message-error-handling-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-apim-98-better-message-error-handling-SNAPSHOT/gravitee-gateway-api-1.48.0-apim-98-better-message-error-handling-SNAPSHOT.zip)
=> APIM-98 add method to easily interrupt body or message flow

src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointConnectorSubscriptionConfiguration.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-65
---
- use it directly by updating your project with version: `2.0.0-apim-65-api-with-webhook-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-65-api-with-webhook-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-65-api-with-webhook-SNAPSHOT.zip)
=> feat: add entrypoint subscription configuration capabilities

pom.xml, src/main/java/io/gravitee/gateway/api/ExecutionContext.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/ConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/context/ContextAttributes.java, src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java, src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-266
Add a deployment context object to pass to connector factory in order to get access to useful component such as api, services, ...
---
- use it directly by updating your project with version: `2.0.0-apim-266-http-proxy-connectors-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-266-http-proxy-connectors-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-266-http-proxy-connectors-SNAPSHOT.zip)
=> feat: add deployment context to connector factory

src/main/java/io/gravitee/gateway/jupiter/api/context/GenericRequest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-349
Add an `originalHost()` to distinguish from `host()` which is allowed to be altered during request processing.
---
- use it directly by updating your project with version: `2.0.0-apim-349-http-host-propagation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-349-http-host-propagation-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-349-http-host-propagation-SNAPSHOT.zip)
=> fix: distinguish host from  original host on request

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java, src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java, src/main/java/io/gravitee/gateway/jupiter/api/service/dlq/DlqService.java, src/main/java/io/gravitee/gateway/jupiter/api/service/dlq/DlqServiceFactory.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-339
This introduce the `DlqService` concept allowing to implement dead letter queue on entrypoint connectors.
---
- use it directly by updating your project with version: `2.1.0-apim-339-dead-letter-queue-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-339-dead-letter-queue-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-339-dead-letter-queue-SNAPSHOT.zip)
=> feat: introduce dlq service concept

src/main/java/io/gravitee/gateway/jupiter/api/context/HttpResponse.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-442
Add new method in the interface to set the content-length header on HTTP response
---
- use it directly by updating your project with version: `2.1.0-apim442-set-content-length-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim442-set-content-length-SNAPSHOT/gravitee-gateway-api-2.1.0-apim442-set-content-length-SNAPSHOT.zip)
=> feat: method to set the content-length header on http response

src/main/java/io/gravitee/gateway/jupiter/api/context/HttpRequest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-339
Add new method in the interface to set the content-length header on HTTP request
---
- use it directly by updating your project with version: `2.1.0-apim442-set-content-length-request-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim442-set-content-length-request-SNAPSHOT/gravitee-gateway-api-2.1.0-apim442-set-content-length-request-SNAPSHOT.zip)
=> feat: method to set the content-length header on http request

src/main/java/io/gravitee/gateway/jupiter/api/exception/MessageProcessingException.java
https://gravitee.atlassian.net/browse/APIM-64
---
- use it directly by updating your project with version: `2.1.0-apim64-eeSecureWebhookEntrypoint-onDlq-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim64-eeSecureWebhookEntrypoint-onDlq-SNAPSHOT/gravitee-gateway-api-2.1.0-apim64-eeSecureWebhookEntrypoint-onDlq-SNAPSHOT.zip)
=> feat: add exception dedicated to message processing failures

src/main/java/io/gravitee/gateway/api/service/Subscription.java, src/main/java/io/gravitee/gateway/api/service/SubscriptionService.java, src/main/java/io/gravitee/gateway/jupiter/api/context/GenericResponse.java, src/test/java/io/gravitee/gateway/jupiter/api/context/GenericResponseTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-373
---
- use it directly by updating your project with version: `2.1.0-apim-373-subscription-error-management-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-373-subscription-error-management-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-373-subscription-error-management-SNAPSHOT.zip)
=> feat: add FAILURE consumer status on Subscription

pom.xml
---
- use it directly by updating your project with version: `2.1.0-remove-gw-api-javadoc-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-remove-gw-api-javadoc-plugin-SNAPSHOT/gravitee-gateway-api-2.1.0-remove-gw-api-javadoc-plugin-SNAPSHOT.zip)
=> chore: remove maven-javadoc-plugin

src/main/java/io/gravitee/gateway/jupiter/api/context/HttpRequest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-466
Add the possibility to set the http method on a HttpRequest
---
- use it directly by updating your project with version: `2.1.0-apim-466-support-http-method-verride-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-466-support-http-method-verride-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-466-support-http-method-verride-SNAPSHOT.zip)
=> feat: add http method setter in HttpRequest

src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/EntrypointConnectorFactory.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-574
Add supportedListenerType to EntrypointConnectorFactory interface to be able to return ListenerType with ConnectorListItem on v4/entrypoints GET  
PR: 
- https://github.com/gravitee-io/gravitee-api-management/pull/2968
---
- use it directly by updating your project with version: `2.1.0-APIM-574-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-APIM-574-SNAPSHOT/gravitee-gateway-api-2.1.0-APIM-574-SNAPSHOT.zip)
=> feat: add supportedListenerType to EntrypointConnectorFactory interface

src/main/java/io/gravitee/gateway/jupiter/api/ApiType.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java, src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnectorFactory.java
Reverting the change on api type in order to properly rename in the future the type, interface in once.
=> fix: revert change on api type

src/main/java/io/gravitee/gateway/api/service/ApiKey.java
**Issue**
https://github.com/gravitee-io/issues/issues/8846
Add `active` field to determine is the ApiKey is active or not. Useful for ApiKey refresher in the gateway.
---
- use it directly by updating your project with version: `1.44.2-8846-API-Subscription-not-working-after-closing-and-re-creating-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.44.2-8846-API-Subscription-not-working-after-closing-and-re-creating-SNAPSHOT/gravitee-gateway-api-1.44.2-8846-API-Subscription-not-working-after-closing-and-re-creating-SNAPSHO …
=> fix: add `active` field

pom.xml, src/main/java/io/gravitee/gateway/jupiter/api/ApiType.java, src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
**Issue**
[APIM-490](https://gravitee.atlassian.net/browse/APIM-490)
Add new attribute in order to store API reactor in the internal attribute.
[APIM-490]: https://gravitee.atlassian.net/browse/APIM-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- use it directly by updating your project with version: `2.1.0-apim-490-add-definition-version-attribute-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-490-add-definition-version-attribute-SNA …
=> feat: add new internal attribute to store apireactor

pom.xml
Bump reporter api version to use latest metrics.
---
- use it directly by updating your project with version: `2.1.0-bump-reporter-api-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-bump-reporter-api-version-SNAPSHOT/gravitee-gateway-api-2.1.0-bump-reporter-api-version-SNAPSHOT.zip)
=> Bump reporter api version

CHANGELOG.md, src/main/java/io/gravitee/gateway/api/service/ApiKey.java
**Issue**
n/a
Merge 1.44.x into master (2.0.0) to be able to merge APIM 3.19.x into 3.20.x 
Some fix in apim 3.19.x need this change. And 3.20.x use 2.0.0 or gateway API 
---
- use it directly by updating your project with version: `2.0.1-merge-1-44-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.1-merge-1-44-x-SNAPSHOT/gravitee-gateway-api-2.0.1-merge-1-44-x-SNAPSHOT.zip)
=> Merge 1.44.x into 2.0.0

CHANGELOG.md, src/main/java/io/gravitee/gateway/api/service/ApiKey.java
**Issue**
n/a
Merge master into alpha to be able to merge 3.20.x into apim master too
---
- use it directly by updating your project with version: `2.1.0-merge-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-merge-master-SNAPSHOT/gravitee-gateway-api-2.1.0-merge-master-SNAPSHOT.zip)
=> Merge master into alpha to be able to merge 3.20.x into apim master too

src/main/java/io/gravitee/gateway/jupiter/api/apiservice/ApiService.java, src/main/java/io/gravitee/gateway/jupiter/api/apiservice/ApiServiceConfiguration.java, src/main/java/io/gravitee/gateway/jupiter/api/apiservice/ApiServiceFactory.java, src/main/java/io/gravitee/gateway/jupiter/api/context/ContextAttributes.java, src/main/java/io/gravitee/gateway/jupiter/api/context/DeploymentContext.java, src/main/java/io/gravitee/gateway/jupiter/api/helper/PluginConfigurationHelper.java, src/test/java/io/gravitee/gateway/jupiter/api/connector/PluginConfigurationHelperTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-605
Add the concept of `ApiService` and refactor `ConnectorHelper` to `PluginConfigurationHelper` to make it usable in other contexts than connectors.
---
- use it directly by updating your project with version: `2.1.0-apim-605-http-healthcheck-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-605-http-healthcheck-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-605-http-healthcheck-SNAPSHOT.zip)
=> feat: introduce api service concept

pom.xml, src/main/java/io/gravitee/gateway/api/http/DefaultHttpHeaders.java, src/main/java/io/gravitee/gateway/jupiter/api/ws/WebSocket.java, src/test/java/io/gravitee/gateway/api/http/DefaultHttpHeadersTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-610
** Description **
Fixe some issues regarding DefaultHttpHeaders implementation while using AsciString instead of String.
Rename a method on the websocket to be accurate with what it actually does.
---
- use it directly by updating your project with version: `2.1.0-apim-610-support-proxy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-610-support-proxy-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-610-support-proxy-SNAPSHOT.zip)
=> APIM-610 support proxy

pom.xml
related to APIM-718
---
- use it directly by updating your project with version: `2.1.0-bump-el-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-bump-el-version-SNAPSHOT/gravitee-gateway-api-2.1.0-bump-el-version-SNAPSHOT.zip)
=> fix: upgrade gio expression language to be consitent with package name

pom.xml, src/test/java/io/gravitee/gateway/reactive/api/connector/entrypoint/async/EntrypointAsyncConnectorImpl.java, src/test/java/io/gravitee/gateway/reactive/api/connector/entrypoint/async/EntrypointAsyncConnectorTest.java
**Issue**
---
- use it directly by updating your project with version: `2.1.0-upgrade-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-upgrade-deps-SNAPSHOT/gravitee-gateway-api-2.1.0-upgrade-deps-SNAPSHOT.zip)
=> fix(deps): upgrade alpha version

src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/EndpointConnectorFactory.java, src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/EndpointConnectorSharedConfiguration.java, src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/EntrypointConnectorFactory.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-724
- adds a EndpointConnectorEndpointGroupConfiguration
- specializes the createConnector method for entrypoint and endpoint, moving them down from ConnectorFactory interface
---
- use it directly by updating your project with version: `2.2.0-apim-724-split-endpoint-configuration-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.2.0-apim-724-split-endpoint-configuration-SNAPSHOT/gravitee-gateway-api-2.2.0-apim-724-split-endpoint-configuration-SNAPSHOT.zip)
=> feat: add endpoint group configuration handling for connector factory

pom.xml, src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/EndpointConnectorFactory.java
Bump el expression version
---
- use it directly by updating your project with version: `3.0.0-bump-expression-language-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-bump-expression-language-SNAPSHOT/gravitee-gateway-api-3.0.0-bump-expression-language-SNAPSHOT.zip)
=> chore: bump el version

src/main/java/io/gravitee/gateway/reactive/api/ws/WebSocket.java
Add `writePing` method to WebSocket interface.
---
- use it directly by updating your project with version: `3.0.0-add-write-ping-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-add-write-ping-SNAPSHOT/gravitee-gateway-api-3.0.0-add-write-ping-SNAPSHOT.zip)
=> feat: add writePing method to WebSocket

pom.xml, src/main/java/io/gravitee/gateway/reactive/api/context/GenericExecutionContext.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-249
Add method to GenericExecution context interface
Big javadoc take time to read !
---
- use it directly by updating your project with version: `3.0.0-ARCHI-249-Add-ExecutionContext-getAttributeAsList-method-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-ARCHI-249-Add-ExecutionContext-getAttributeAsList-method-SNAPSHOT/gravitee-gateway-api-3.0.0-ARCHI-249-Add-ExecutionContext-getAttributeAsList-method-SNAPSHOT.zip)
=> Archi 249 add execution context get attribute as list method

src/main/java/io/gravitee/gateway/reactive/api/context/GenericExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableMessage.java
**Issue**
APIM-1622
Some policies are using Freemarker as template engine, to keep the same syntaxe to access the Message attributes (`message.content` / `message.headers['my-header'][0]` ) the attributes accessor need to follow the Java getter syntaxe.
---
- use it directly by updating your project with version: `3.0.0-fix-evaluable-message-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-fix-evaluable-message-SNAPSHOT/gravitee-gateway-api-3.0.0-fix-evaluable-message-SNAPSHOT.zip)
=> Fix evaluable message

src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/async/EndpointAsyncConnector.java
fix APIM-323
---
- use it directly by updating your project with version: `3.0.0-apim-323-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-apim-323-SNAPSHOT/gravitee-gateway-api-3.0.0-apim-323-SNAPSHOT.zip)
=> fix: define common ERROR KEY for AsyncEndpoints

src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/async/EndpointAsyncConnector.java, src/main/java/io/gravitee/gateway/reactive/api/policy/SecurityToken.java
Add invalid security token used when a policy wants to express the fact that a token has been extracted but is invalid
=> feat: add invalid state on SecurityToken

pom.xml, src/main/java/io/gravitee/gateway/reactive/api/message/DefaultMessage.java, src/main/java/io/gravitee/gateway/reactive/api/message/Message.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2552
Allow to get message attribute as a list
---
- use it directly by updating your project with version: `3.1.0-apim-2552-kafka-topic-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.1.0-apim-2552-kafka-topic-SNAPSHOT/gravitee-gateway-api-3.1.0-apim-2552-kafka-topic-SNAPSHOT.zip)
=> feat: add method to get list from an message attribute

src/main/java/io/gravitee/gateway/api/ExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/InternalContextAttributes.java
sync commit merged on alpha by mistake 
---
- use it directly by updating your project with version: `3.2.0-alpha-rebased-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.2.0-alpha-rebased-SNAPSHOT/gravitee-gateway-api-3.2.0-alpha-rebased-SNAPSHOT.zip)
=> feat: add support for DBLess mode

pom.xml
Bump dependencies
---
- use it directly by updating your project with version: `3.2.1-bump-dependencies-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.2.1-bump-dependencies-SNAPSHOT/gravitee-gateway-api-3.2.1-bump-dependencies-SNAPSHOT.zip)
=> chore(deps): bump dependencies

src/main/java/io/gravitee/gateway/reactive/api/ExecutionFailure.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-267
Allow to instantiate an ExecutionFailure without a status code.
This is useful when you need to interrupt the chain in the context of an tcp-proxy api, which is not related with HTTP status
---
- use it directly by updating your project with version: `3.4.0-archi-267-tcp-proxy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.4.0-archi-267-tcp-proxy-SNAPSHOT/gravitee-gateway-api-3.4.0-archi-267-tcp-proxy-SNAPSHOT.zip)
=> feat: allow to create ExecutionFailure without status code

src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java, src/main/java/io/gravitee/gateway/jupiter/api/el/EvaluableRequest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3507
evaluate remote address instead of local
---
- use it directly by updating your project with version: `2.0.2-apim-3507-fix-remote-address-evaluation-2-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.2-apim-3507-fix-remote-address-evaluation-2-0-x-SNAPSHOT/gravitee-gateway-api-2.0.2-apim-3507-fix-remote-address-evaluation-2-0-x-SNAPSHOT.zip)
=> fix: evaluate remote address instead of local

src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java, src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableRequest.java
Although the change adds a feature to our EL syntax, this is committed as a fix to ease back-porting the feature to older versions
---
- use it directly by updating your project with version: `3.4.2-feat-add-host-to-el-request-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.4.2-feat-add-host-to-el-request-SNAPSHOT/gravitee-gateway-api-3.4.2-feat-add-host-to-el-request-SNAPSHOT.zip)
=> fix: add host property to el requests

src/main/java/io/gravitee/gateway/reactive/api/context/ContextAttributes.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-6046
Message reporting works in different way than request/response so that there is a need to add a key in context attributes to pass api name to a reporter
---
- use it directly by updating your project with version: `3.5.1-APIM-6046-message-reporters-lacking-api-name-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.5.1-APIM-6046-message-reporters-lacking-api-name-SNAPSHOT/gravitee-gateway-api-3.5.1-APIM-6046-message-reporters-lacking-api …
=> fix: Message reporters lacking api name value

pom.xml
Update gravitee-reporter-api
---
- use it directly by updating your project with version: `3.5.2-fix-deps-bump-gravitee-reporter-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.5.2-fix-deps-bump-gravitee-reporter-api-SNAPSHOT/gravitee-gateway-api-3.5.2-fix-deps-bump-gravitee-reporter-api-SNAPSHOT.zip)
=> fix(deps): Bump gravitee-reporter-api to version 1.31.2

src/main/java/io/gravitee/gateway/reactive/api/context/GenericRequest.java, src/main/java/io/gravitee/gateway/reactive/api/context/TlsSession.java
https://gravitee.atlassian.net/browse/APIM-3987
---
- use it directly by updating your project with version: `3.8.0-apim-3987-tls-session-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.8.0-apim-3987-tls-session-SNAPSHOT/gravitee-gateway-api-3.8.0-apim-3987-tls-session-SNAPSHOT.zip)
=> feat: deprecate SslSession in favor of TlsSession

src/main/java/io/gravitee/gateway/api/service/Subscription.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-6600
Add environmentId in subscription model
---
- use it directly by updating your project with version: `3.5.1-apim-6600-add-envid-in-subscription-350-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.5.1-apim-6600-add-envid-in-subscription-350-SNAPSHOT/gravitee-gateway-api-3.5.1-apim-6600-add-envid-in-subscription-350-SNAPSHOT.zip)
=> fix: add environmentId in subscription [ 3.5.x ]

src/main/java/io/gravitee/gateway/api/service/Subscription.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-6600
Add environmentId in subscription
---
- use it directly by updating your project with version: `3.8.1-apim-6600-add-envid-in-subscription-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.8.1-apim-6600-add-envid-in-subscription-SNAPSHOT/gravitee-gateway-api-3.8.1-apim-6600-add-envid-in-subscription-SNAPSHOT.zip)
=> fix: add environmentId in subscription [ 3.8.x ]

src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseMessageExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseMessageRequest.java, src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseMessageResponse.java, src/main/java/io/gravitee/gateway/reactive/api/context/http/HttpMessageExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/http/HttpMessageRequest.java, src/main/java/io/gravitee/gateway/reactive/api/context/http/HttpPlainResponse.java, src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableRequest.java, src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableResponse.java, src/main/java/io/gravitee/gateway/reactive/api/hook/Hook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/HttpHook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/InvokerHook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/MessageHook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/PolicyHook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/ProcessorHook.java, src/main/java/io/gravitee/gateway/reactive/api/hook/SecurityPlanHook.java, src/main/java/io/gravitee/gateway/reactive/api/policy/Policy.java, src/main/java/io/gravitee/gateway/reactive/api/policy/SecurityPolicy.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7109
Fix/complete the new HTTP-oriented interfaces to prepare for APIM to switch to the new interfaces internally.
---
- use it directly by updating your project with version: `3.9.0-apim-7109-switch-to-new-ctx-interfaces-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7109-switch-to-new-ctx-interfaces-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7109-switch-to-new-ctx-interfaces-SNAPSHOT.zip)
=> fix: adapt interfaces to prepare for apim switch

src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableRequest.java, src/main/java/io/gravitee/gateway/reactive/api/el/EvaluableResponse.java, src/test/java/io/gravitee/gateway/reactive/api/el/EvaluableRequestTest.java, src/test/java/io/gravitee/gateway/reactive/api/el/EvaluableResponseTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7109
Reintroduce and deprecate previous constructors so old policies can still be used before migrating to the new context interfaces.
---
- use it directly by updating your project with version: `3.9.0-fix-evaluable-request-response-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-fix-evaluable-request-response-SNAPSHOT/gravitee-gateway-api-3.9.0-fix-evaluable-request-response-SNAPSHOT.zip)
=> fix: restore previous constructor as deprecated

pom.xml, src/main/java/io/gravitee/gateway/api/service/ApiKeyService.java, src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java, src/main/java/io/gravitee/gateway/reactive/api/policy/SecurityToken.java, src/main/java/io/gravitee/gateway/reactive/api/policy/kafka/KafkaSecurityPolicy.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7143
- Add a new KafkaConnectionContext to be used to authenticate a connection
- Add required methods in the KafkaSecurityPolicy to be able to handle authentication
---
- use it directly by updating your project with version: `3.9.0-apim-7143-impl-security-chain-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7143-impl-security-chain-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7143-impl-security-chain-SNAPSHOT.zip)
=> Add elements to implement native security chain

src/main/java/io/gravitee/gateway/reactive/api/ListenerType.java
**Issue**
Add `KAFKA` as a possible enum for `ListenerType`.
---
- use it directly by updating your project with version: `3.9.0-apim-7152-add-kafka-listener-type-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7152-add-kafka-listener-type-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7152-add-kafka-listener-type-SNAPSHOT.zip)
=> feat: add kafka as listener type

src/main/java/io/gravitee/gateway/reactive/api/ApiType.java
**Issue**
Add `NATIVE` to `ApiType` enum.
---
- use it directly by updating your project with version: `3.9.0-apim-7152-add-native-api-type-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7152-add-native-api-type-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7152-add-native-api-type-SNAPSHOT.zip)
=> feat: add native to api type enum

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaMessageExecutionContext.java
**Issue**
N/A
access KafkaPrincipal from Kafka contexts
---
- use it directly by updating your project with version: `3.9.0-handle-principal-in-kafka-context-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-handle-principal-in-kafka-context-SNAPSHOT/gravitee-gateway-api-3.9.0-handle-principal-in-kafka-context-SNAPSHOT.zip)
=> feat: access KafkaPrincipal from KafkaContext

src/main/java/io/gravitee/gateway/reactive/api/message/DefaultMessage.java
In some cases where external component wants to add tracing attributes, the map could be null. This PR attempts to fix it.
---
- use it directly by updating your project with version: `3.9.0-fix-init-tracing-attributes-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-fix-init-tracing-attributes-SNAPSHOT/gravitee-gateway-api-3.9.0-fix-init-tracing-attributes-SNAPSHOT.zip)
=> fix: init tracing attributes if necessary when adding new attributes

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaRequest.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaResponse.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/NetworkController.java
A FlowController interface is added to KafkaExecutionContext. It can be used from inside a Policy to stop/resume the acceptance of new requests. It has been introduced for Kafka Quota Policy to handle throttling: when we detect the quota limit has been reached, the GW will stop accepting requests until the throttling time has passed.
A new method, `addActionOnResponse`, has been added to `KafkaExecutionContext` to register a callback that must be applied on the response. This allows to work on the response inside `onRequest` method of a policy.
`notifyChange` method was declared in an internal interface, but when a policy updates the request and/or response, we need to call it from inside the policy to ensure the request/response is rebuilt.
--- …
=> feat: access to NetworkController in KafkaExecutionContext

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java
This method should not be callable from Policy's code. It needs to be moved in the internal interface.
---
- use it directly by updating your project with version: `3.9.0-remove-method-from-kafka-execution-context-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-remove-method-from-kafka-execution-context-SNAPSHOT/gravitee-gateway-api-3.9.0-remove-method-from-kafka-execution-context-SNAPSHOT.zip)
=> fix: remove getOnResponseActions from KafkaExecutionContext

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaMessageExecutionContext.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7139
add TemplateEngine for native Kafka
? i'm wonder if we can use the `BaseMessageExecutionContext` to extends `NativeMessageExecutionContext` but i'm not sure about interruptMessages stuff. maybe we can see it later when we know how to interrupt messages 
---
- use it directly by updating your project with version: `3.9.0-APIM-7139-TemplateEngine-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-APIM-7139-TemplateEngine-SNAPSHOT/gravitee-gat …
=> feat: add TemplateEngine for native Kafka

src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/http/HttpPlainExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7719
Juste add String used by this PR https://github.com/gravitee-io/gravitee-reactor-native-kafka/pull/41
Similar to KafkaExecutionContext but for Connection
---
- use it directly by updating your project with version: `3.9.0-APIM-7719-template-engine-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-APIM-7719-template-engine-SNAPSHOT/gravitee-gateway-api-3.9.0-APIM-7719-template-engine-SNAPSHOT.zip)
=> feat: add TemplateEngine for KafkaConnectionContext

src/main/java/io/gravitee/gateway/reactive/api/ConnectorMode.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7165
Add `interact` to configure it on kafka endpoints and entrypoints. which will allow the PolicyStudio phases to be compatible with
I hesitate to add `connect` immediately WDYT? 
Then update APIM then update connector-native-kafka then APIM again 
---
- use it directly by updating your project with version: `3.9.0-APIM-7162-interact-connectorMode-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-APIM-7162-interact-connectorMode-SNAPSHOT/grav …
=> feat: add interact in ConnectorMode

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java, src/main/java/io/gravitee/gateway/reactive/api/exception/base/BaseExecutionFailure.java, src/main/java/io/gravitee/gateway/reactive/api/exception/base/NativeExecutionFailure.java, src/main/java/io/gravitee/gateway/reactive/api/exception/kafka/KafkaExecutionFailure.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7533
add interruptWith with KafkaExecutionFailure
Uses the same structure as for context. but the refactoring with the "HTTP part" will have to be done later
---
- use it directly by updating your project with version: `3.9.0-APIM-7533-interruptionWith-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-APIM-7533-interruptionWith-SNAPSHOT/gravitee-gateway-api-3.9.0-APIM-7533-interruptionWith-SNAPSHOT.zip)
=> Kafka: add interruptWith with KafkaExecutionFailure

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-7136
Access to Kafka connection context from execution context
---
- use it directly by updating your project with version: `3.9.0-apim7136-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim7136-SNAPSHOT/gravitee-gateway-api-3.9.0-apim7136-SNAPSHOT.zip)
=> feat: access to Kafka connection context from execution context

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaMessageExecutionContext.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-8108
Access to KafkaExecution Context from KafkaMessageExecutionContext
---
- use it directly by updating your project with version: `3.9.1-apim8108-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.1-apim8108-SNAPSHOT/gravitee-gateway-api-3.9.1-apim8108-SNAPSHOT.zip)
=> fix: access Kafka execution context from KafkaMessageExecutionContext

src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaConnectionContext.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/topicidentity/TopicIdentity.java, src/main/java/io/gravitee/gateway/reactive/api/context/kafka/topicidentity/TopicIdentityRegistry.java, src/main/java/io/gravitee/gateway/reactive/api/policy/kafka/KafkaPolicy.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-8332
https://gravitee.atlassian.net/browse/APIM-8335
Add interface for kafka TopicIdentityRegistry
Add onInitialize to KafkaPolicy
Expected for 4.6.x and next 4.7.x 
---
- use it directly by updating your project with version: `3.10.0-APIM-8332-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.10.0-APIM-8332-SNAPSHOT/gravitee-gateway-api-3.10.0-APIM-8332-SNAPSHOT.zip)
=> Add TopicIdentity concept capable of initialising itself before executing a any policy chain

.circleci/config.yml, .github/renovate.json, pom.xml
Bump dependencies.
Especially the `json-smart` one to fix a vulnerability in APIM
---
- use it directly by updating your project with version: `3.11.1-bump-dependencies-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.11.1-bump-dependencies-SNAPSHOT/gravitee-gateway-api-3.11.1-bump-dependencies-SNAPSHOT.zip)
=> Bump dependencies

src/main/java/io/gravitee/gateway/reactive/api/message/kafka/KafkaMessage.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-8989
Add key setter methods to KafkaMessage interface.
**Note:** Do we need an overloaded setter for the Kafka key accepting a String ???
---
- use it directly by updating your project with version: `3.12.0-APIM-8989-add-key-setter-methods-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.12.0-APIM-8989-add-key-setter-methods-SNAPSHOT/gravitee-gateway-api-3.12.0-APIM-8989-add-key-setter-methods-SNAPSHOT.zip)
=> feat(kafka): add key setter methods to KafkaMessage interface

src/main/java/io/gravitee/gateway/reactive/api/ApiType.java
**Issue**
Add LLM & MCP API types.
---
- use it directly by updating your project with version: `4.1.0-llm-proxy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/4.1.0-llm-proxy-SNAPSHOT/gravitee-gateway-api-4.1.0-llm-proxy-SNAPSHOT.zip)
---
- use it directly by updating your project with version: `4.1.0-llm-proxy-SNAPSHOT`
- download …
=> feat: add llm-proxy api type
