- pom.xml
This closes gravitee-io/issues#113
> feat(analytics): update gravitee-reporter-api to handle proxy latency data

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> feat(plan): Implementation of Plans

- src/main/java/io/gravitee/gateway/api/Request.java
> feat(gateway): Add pathInfos (complete path without context-path)

- src/main/java/io/gravitee/gateway/api/Request.java
> feat(gateway): Manage a request transaction ID from headers

- src/main/java/io/gravitee/gateway/api/http/stream/TransformableRequestStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableRequestStreamBuilder.java
> feat(gateway): Add a transformable request content builder

- src/main/java/io/gravitee/gateway/api/http/stream/TransformableRequestStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableResponseStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableResponseStreamBuilder.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableStreamBuilder.java
- src/main/java/io/gravitee/gateway/api/stream/TransformableStream.java
> fix(gateway): Refactor streamable API for HTTP content

- src/main/java/io/gravitee/gateway/api/endpoint/EndpointManager.java
> feat(gateway): Multi-tenant support

- pom.xml
- src/main/java/io/gravitee/gateway/api/Request.java
> fix(gateway): Update model to handle multiple values per query parameter

- src/main/java/io/gravitee/gateway/api/Invoker.java
- src/main/java/io/gravitee/gateway/api/http/client/HttpClient.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyConnection.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
> feat(gateway): Update the Invoker and Proxy API

- pom.xml
- src/main/java/io/gravitee/gateway/api/Request.java
> refactor(reporter): Log and metrics reporting

- appveyor.yml
> chore: add windows build based on AppVeyor

- pom.xml
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableRequestStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableResponseStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableSourceStream.java
- src/main/java/io/gravitee/gateway/api/http/stream/TransformableStreamBuilder.java
- src/main/java/io/gravitee/gateway/api/stream/TransformableStream.java
> fix(gateway): Make the policy fails in case of streaming issue

- src/main/java/io/gravitee/gateway/api/expression/TemplateVariableProvider.java
Closes gravitee-io/issues#1048
> fix(gateway): Performance improvements

- pom.xml
- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java
Closes gravitee-io/issues#1193
> fix(http): Add a specific enum value to handle unknown HTTP Method

- src/main/java/io/gravitee/gateway/api/endpoint/Endpoint.java
- src/main/java/io/gravitee/gateway/api/lb/LoadBalancerStrategy.java
> feat(gateway): Manage group of endpoints

- src/main/java/io/gravitee/gateway/api/Request.java
Closes gravitee-io/issues#1355
> feat(gateway) Add the protocol scheme to the request

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
This closes gravitee-io/issues#1312
> feat: display top paths/resources in analytics

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
Closes gravitee-io/issues#1622
> feat(gateway): Performance improvements

- src/main/java/io/gravitee/gateway/api/expression/TemplateEngine.java
closes gravitee-io/issues#1820
> feat(el): add parse method to TemplateEngine to work with generic data type

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
Closes gravitee-io/issues#1922
> feat(gateway): Attach the sslsession to the request

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
This closes gravitee-io/issues#1948
> feat: Audit on API user from JWT

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
- src/main/java/io/gravitee/gateway/api/Response.java
Closes gravitee-io/issues#1834
> feat(http): Add server request timeout

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyResponse.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java
- src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequestImpl.java
- src/main/java/io/gravitee/gateway/api/ws/WebSocket.java
- src/main/java/io/gravitee/gateway/api/ws/WebSocketFrame.java
Closes gravitee-io/issues#1899
> feat(http): Add websocket support

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> feat(role): Add a new key in context attributes to manage roles

- pom.xml
This closes gravitee-io/issues#1997
> feat: Multi analytics dashboards

- pom.xml
> fix(spel): manage null result

- pom.xml
- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> fix(requests): do not encode/decode query parameters by default

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
- src/main/java/io/gravitee/gateway/api/http2/HttpFrame.java
- src/main/java/io/gravitee/gateway/api/http2/HttpFrameImpl.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyConnection.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyResponse.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java
- src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequestImpl.java
Closes gravitee-io/issues#3105
> feat(grpc): Add GRPC support

- src/main/java/io/gravitee/gateway/api/endpoint/AbstractEndpoint.java
- src/main/java/io/gravitee/gateway/api/endpoint/Endpoint.java
- src/main/java/io/gravitee/gateway/api/endpoint/EndpointAvailabilityListener.java
Closes gravitee-io/issues#3877
> feat(endpoint): Manage secondary endpoints

- src/main/java/io/gravitee/gateway/api/ws/WebSocketFrame.java
Closes gravitee-io/issues#4220
> fix(websocket): Add support for final frame

- src/main/java/io/gravitee/gateway/api/proxy/ProxyConnection.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyResponse.java
Closes gravitee-io/issues#4648
> fix(gateway): Add handler when cancelling a proxy response.

- src/main/java/io/gravitee/gateway/api/el/EvaluableExtractor.java
> feat: add utils class to generate base for spel grammar 

- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java
Closes gravitee-io/issues#4837
> fix(gateway): URI as a string

- pom.xml
Closes gravitee-io/issues#4769
> feat(assign-metrics): use custom metrics in reporter

- src/main/java/io/gravitee/gateway/api/endpoint/resolver/EndpointResolver.java
- src/main/java/io/gravitee/gateway/api/endpoint/resolver/ProxyEndpoint.java
- src/main/java/io/gravitee/gateway/api/proxy/ProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestImpl.java
Closes gravitee-io/issues#5268
> feat(gateway): Provide a way to retrieve an endpoint

- .circleci/config.yml
- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
> feat(gateway): add api.deployedAt to context

- pom.xml
- src/main/java/io/gravitee/gateway/api/Connector.java
- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
- src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequest.java
- src/main/java/io/gravitee/gateway/api/proxy/ws/WebSocketProxyRequestImpl.java
- src/main/java/io/gravitee/gateway/api/ws/WebSocket.java
Related to gravitee-io/issues#5220
> chore(vertx4): move to gravitee-bom and use vertx4.

- pom.xml
- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
- src/main/java/io/gravitee/gateway/api/context/SimpleExecutionContext.java
- src/main/java/io/gravitee/gateway/api/stream/ReadWriteStream.java
Closes gravitee-io/issues#1581
> feat(tracing): Provide initial support for Tracing

- src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java
Closes gravitee-io/issues#6051
> fix(el): reintroduce request.method access

- pom.xml
- src/main/java/io/gravitee/gateway/api/el/EvaluableExtractor.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableRequest.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableSSLPrincipal.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableSSLSession.java
- src/test/java/io/gravitee/gateway/api/el/EvaluableExtractorTest.java
- src/test/java/io/gravitee/gateway/api/el/EvaluableSSLSessionTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> feat: allow access to SSL attributes in EL TemplateEngine

- pom.xml
- src/main/java/io/gravitee/gateway/api/el/EmptyEvaluableSSLPrincipal.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableExtractor.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableSSLPrincipal.java
- src/main/java/io/gravitee/gateway/api/el/EvaluableSSLSession.java
- src/test/java/io/gravitee/gateway/api/el/EvaluableSSLSessionTest.java
> fix: remove `get` and `getAll` methods and replace with `getAttributes`

- src/main/java/io/gravitee/gateway/api/Response.java
> refactor: add default end implementation

- src/main/java/io/gravitee/gateway/api/Request.java
- src/main/java/io/gravitee/gateway/api/RequestWrapper.java
Closes gravitee-io/issues#6574
> feat: add method to access request's host

- src/main/java/io/gravitee/gateway/api/proxy/builder/ProxyRequestBuilder.java
Closes gravitee-io/issues#6915
> fix(proxy): Do not rewrite the URI if there is no duplicated slash

- src/main/java/io/gravitee/gateway/api/context/SimpleExecutionContext.java
**Issue**
https://github.com/gravitee-io/issues/issues/7228
> fix: implement containsKey of AttributeMap

- src/main/java/io/gravitee/gateway/api/context/SimpleExecutionContext.java
**Issue**
https://github.com/gravitee-io/issues/issues/7268
> Merge 1.32.1

- src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/context/Request.java
- src/main/java/io/gravitee/gateway/reactive/api/context/Response.java
- src/main/java/io/gravitee/gateway/reactive/api/context/sync/SyncRequest.java
- src/main/java/io/gravitee/gateway/reactive/api/context/sync/SyncResponse.java
> feat(jupiter): add some javadoc

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/ExecutionFailure.java
- src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
Manage chain interruption
---
- use it directly by updating your project with version: `1.33.0-prototype-reactive-interuption-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.33.0-prototype-reactive-interuption-SNAPSHOT/gravitee-gateway-api-1.33.0-prototype-reactive-interuption-SNAPSHOT.zip)
> feat(jupiter): handle interruption mechanism

- src/main/java/io/gravitee/gateway/reactive/api/context/Request.java
- src/main/java/io/gravitee/gateway/reactive/api/context/Response.java
Rework `body` / `chunks` methods to improve body consumption.
> feat(jupiter): better handling of request and response body

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/context/RequestExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/el/EvaluableRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/el/EvaluableResponse.java
Allows to access request or response content from el expression
---
- use it directly by updating your project with version: `1.34.0-jupiter-el-expression-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.34.0-jupiter-el-expression-SNAPSHOT/gravitee-gateway-api-1.34.0-jupiter-el-expression-SNAPSHOT.zip)
> feat(jupiter): request & response content support in EL

- pom.xml
- src/main/java/io/gravitee/gateway/api/http/HttpHeaders.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/ExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/Response.java
- src/main/java/io/gravitee/gateway/jupiter/api/hook/Hook.java
- src/main/java/io/gravitee/gateway/jupiter/api/hook/SecurityPlanHook.java
- src/test/java/io/gravitee/gateway/api/http/HttpHeadersTest.java
Implement debug mode for jupiter
---
- use it directly by updating your project with version: `1.35.0-jupiter-debug-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.35.0-jupiter-debug-SNAPSHOT/gravitee-gateway-api-1.35.0-jupiter-debug-SNAPSHOT.zip)
> Jupiter debug

- CHANGELOG.md
- src/main/java/io/gravitee/gateway/api/http/DefaultHttpHeaders.java
- src/main/java/io/gravitee/gateway/api/http/HttpHeaders.java
- src/test/java/io/gravitee/gateway/api/http/DefaultHttpHeadersTest.java
- src/test/java/io/gravitee/gateway/api/http/HttpHeadersTest.java
**Issue**
NA
Merge 1.32.x into master
---
- use it directly by updating your project with version: `1.36.1-merge-1-32-x-into-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.36.1-merge-1-32-x-into-master-SNAPSHOT/gravitee-gateway-api-1.36.1-merge-1-32-x-into-master-SNAPSHOT.zip)
> Merge 1.32.x into master

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/Subscription.java
- src/main/java/io/gravitee/gateway/jupiter/api/ApiType.java
- src/main/java/io/gravitee/gateway/jupiter/api/ConnectorMode.java
- src/main/java/io/gravitee/gateway/jupiter/api/ExecutionPhase.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/HttpExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/HttpRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/HttpResponse.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/MessageRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/MessageResponse.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/Request.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/RequestExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/Response.java
- src/main/java/io/gravitee/gateway/jupiter/api/el/EvaluableRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/endpoint/EndpointConnectorConfiguration.java
- src/main/java/io/gravitee/gateway/jupiter/api/endpoint/EndpointConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/endpoint/sync/EndpointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/entrypoint/EntrypointConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/entrypoint/EntrypointConnectorConfiguration.java
- src/main/java/io/gravitee/gateway/jupiter/api/entrypoint/EntrypointConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/entrypoint/sync/EntrypointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/hook/Hook.java
- src/main/java/io/gravitee/gateway/jupiter/api/policy/Policy.java
- src/main/java/io/gravitee/gateway/jupiter/api/policy/SecurityPolicy.java
**Issue**
https://github.com/gravitee-io/issues/issues/8238
https://github.com/gravitee-io/issues/issues/8009
Update context and policy api to properly handle message/async excecution
---
- use it directly by updating your project with version: `1.38.0-8238-entrypoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.38.0-8238-entrypoint-SNAPSHOT/gravitee-gateway-api-1.38.0-8238-entrypoint-SNAPSHOT.zip)
> 8238 entrypoint

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/endpoint/EndpointConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/endpoint/sync/EndpointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/exception/PluginConfigurationException.java
- src/test/java/io/gravitee/gateway/jupiter/api/endpoint/EndpointConnectorFactoryTest.java
feat: EndpointConnectorFactory deserializes endpoint plugin configuration
**Issue**
https://github.com/gravitee-io/issues/issues/8229
---
- use it directly by updating your project with version: `1.39.0-feat-endpoint-connector-factory-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.39.0-feat-endpoint-connector-factory-SNAPSHOT/gravitee-gateway-api-1.39.0-feat-endpoint-connector-factory-SNAPSHOT.zip)
> feat: EndpointConnectorFactory deserializes endpoint plugin configuration

- src/main/java/io/gravitee/gateway/api/service/SubscriptionService.java
- src/main/java/io/gravitee/gateway/jupiter/api/policy/SecurityPolicy.java
- src/main/java/io/gravitee/gateway/jupiter/api/policy/SecurityToken.java
**Issue**
https://github.com/gravitee-io/issues/issues/7991
---
- use it directly by updating your project with version: `1.39.0-feat-jupiterPlans-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.39.0-feat-jupiterPlans-SNAPSHOT/gravitee-gateway-api-1.39.0-feat-jupiterPlans-SNAPSHOT.zip)
> feat: introduce generic SecurityToken to handle ApiKey and clientId tokens

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/Subscription.java
- src/main/java/io/gravitee/gateway/jupiter/api/ListenerType.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/EntrypointConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/ExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
**Issue**
https://github.com/gravitee-io/issues/issues/8026
---
- use it directly by updating your project with version: `1.43.0-webhook-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.43.0-webhook-SNAPSHOT/gravitee-gateway-api-1.43.0-webhook-SNAPSHOT.zip)
> Initial support for webhook subscription

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java
- Kafka now set the id based on record information
**Issue**
https://github.com/gravitee-io/issues/issues/8262
> feat(message): add identifier on message

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/EntrypointConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/ContextAttributes.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/MessageRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/MessageResponse.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/Response.java
**Issue**
https://github.com/gravitee-io/issues/issues/8403
fix onMessage composition.
> fix: message level policy

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
**Issue**
https://github.com/gravitee-io/issues/issues/8037
Add internal attributes for Async API features
---
- use it directly by updating your project with version: `1.46.2-attributes-for-sme-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.46.2-attributes-for-sme-SNAPSHOT/gravitee-gateway-api-1.46.2-attributes-for-sme-SNAPSHOT.zip)
>  add missing attributes to handle properly AsyncAPI

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/connector/Connector.java
Add id for Connector in order to be able to use it when resolving flow for api V4.
> feat(v4): add identifier on Connector

- pom.xml
- src/main/java/io/gravitee/gateway/api/buffer/Buffer.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/GenericExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/MessageExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/el/EvaluableMessage.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java
- src/main/java/io/gravitee/gateway/jupiter/api/policy/Policy.java
- src/test/java/io/gravitee/gateway/jupiter/api/message/DefaultMessageTest.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-173
Add required methods for supporting condition at message level + some cleanup & javadoc improvements
---
- use it directly by updating your project with version: `1.48.0-apim-173-condition-message-level-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-apim-173-condition-message-level-SNAPSHOT/gravitee-gateway-api-1.48.0-apim-173-condition-message-level-SNAPSHOT.zip)
> feat: add support for condition at message level

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/connector/ConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java
- src/main/java/io/gravitee/gateway/jupiter/api/qos/Qos.java
- src/main/java/io/gravitee/gateway/jupiter/api/qos/QosOptions.java
**Issue**
[APIM-100](https://graviteecommunity.atlassian.net/browse/APIM-100)
First implementation that brings QoS conception for Async Api V4.
---
- use it directly by updating your project with version: `1.48.0-qos-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/1.48.0-qos-SNAPSHOT/gravitee-gateway-api-1.48.0-qos-SNAPSHOT.zip)
> APIM-100 Introduce Qos concept for api V4

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/Subscription.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-307
Filter attribute is no more required as is and be part of the metadata.
---
- use it directly by updating your project with version: `2.0.0-apim-307-message-filtering-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-307-message-filtering-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-307-message-filtering-SNAPSHOT.zip)
> APIM-307 Remove unused filter attribute from Subscription

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/Subscription.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-141
---
- use it directly by updating your project with version: `2.0.0-apim-141-subscriptionEquals-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.0.0-apim-141-subscriptionEquals-SNAPSHOT/gravitee-gateway-api-2.0.0-apim-141-subscriptionEquals-SNAPSHOT.zip)
> feat: add subscription.equals using lombok

- pom.xml
- src/main/java/io/gravitee/gateway/jupiter/api/ApiType.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/async/EndpointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/endpoint/sync/EndpointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/async/EntrypointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnector.java
- src/main/java/io/gravitee/gateway/jupiter/api/connector/entrypoint/sync/EntrypointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/GenericExecutionContext.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/GenericRequest.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/HttpResponse.java
- src/main/java/io/gravitee/gateway/jupiter/api/context/InternalContextAttributes.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
- src/main/java/io/gravitee/gateway/jupiter/api/message/Message.java
- src/test/java/io/gravitee/gateway/jupiter/api/message/DefaultMessageTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
---
- use it directly by updating your project with version: `2.1.0-support-v4-logging-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-support-v4-logging-SNAPSHOT/gravitee-gateway-api-2.1.0-support-v4-logging-SNAPSHOT.zip)
> APIM-490: Support of metrics/logging on api v4

- src/main/java/io/gravitee/gateway/jupiter/api/message/DefaultMessage.java
- src/test/java/io/gravitee/gateway/jupiter/api/message/DefaultMessageTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-790
- sourceTimestamp is only added to metadata when using the builder
- if sourceTimestamp is not assigned by the user, then it defaults to timestamp
---
- use it directly by updating your project with version: `2.1.0-apim-790-source-timestamp-message-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/2.1.0-apim-790-source-timestamp-message-SNAPSHOT/gravitee-gateway-api-2.1.0-apim-790-source-timestamp-message-SNAPSHOT.zip)
> feat: enhance DefaultMessage builder to manage sourceTimestamp

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/ApiKeyService.java
- src/main/java/io/gravitee/gateway/api/service/SubscriptionService.java
https://gravitee.atlassian.net/browse/ARCHI-212
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-vruktmvtos.chromatic.com)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.z6.web.core.windows.net/archi-212/index.html)
_Notes_: The deployed app is linked to the management API of APIM master. (Same login and password as APIM master)
---
- use it directly by updating your project with version: `3.0.0-archi-212-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway …
> ARCHI-212 Improve APIM sync process

- pom.xml
- src/main/java/io/gravitee/gateway/api/service/ApiKey.java
Just add equals and hashcode on api key model.
> ARCHI-217: add equals and hash code on api key

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/context/InternalContextAttributes.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2335
---
- use it directly by updating your project with version: `3.0.0-db-less-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.0.0-db-less-SNAPSHOT/gravitee-gateway-api-3.0.0-db-less-SNAPSHOT.zip)
> feat: add support for DBLess mode

- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/context/ContextAttributes.java
see https://gravitee.atlassian.net/browse/APIM-3494
---
- use it directly by updating your project with version: `3.5.0-feat-mapped-path-attribute-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.5.0-feat-mapped-path-attribute-SNAPSHOT/gravitee-gateway-api-3.5.0-feat-mapped-path-attribute-SNAPSHOT.zip)
> feat: add mapped path attribute to context

- src/main/java/io/gravitee/gateway/api/service/Subscription.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3983
---
- use it directly by updating your project with version: `3.6.0-apim-3983-gateway-subscription-truststore-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.6.0-apim-3983-gateway-subscription-truststore-SNAPSHOT/gravitee-gateway-api-3.6.0-apim-3983-gateway-subscription-truststore-SNAPSHOT.zip)
> feat: add client certificate on subscription object

- src/main/java/io/gravitee/gateway/reactive/api/policy/SecurityToken.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3985
---
- use it directly by updating your project with version: `3.7.0-apim-3985-mtls-security-plan-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.7.0-apim-3985-mtls-security-plan-SNAPSHOT/gravitee-gateway-api-3.7.0-apim-3985-mtls-security-plan-SNAPSHOT.zip)
> feat: introduce CERTIFICATE security token type

- pom.xml
- src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaMessageRequest.java
- src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaMessageResponse.java
- src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaRequest.java
- src/main/java/io/gravitee/gateway/reactive/api/context/kafka/KafkaResponse.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7132
---
- use it directly by updating your project with version: `3.9.0-apim-7132-handle-simple-kafka-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7132-handle-simple-kafka-api-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7132-handle-simple-kafka-api-SNAPSHOT.zip)
> feat: enrich KafkaExecutionContext with request and response

- pom.xml
- src/main/java/io/gravitee/gateway/api/ExecutionContext.java
- src/main/java/io/gravitee/gateway/api/context/SimpleExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/ExecutionPhase.java
- src/main/java/io/gravitee/gateway/reactive/api/context/InternalContextAttributes.java
- src/main/java/io/gravitee/gateway/reactive/api/context/base/BaseExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/hook/HttpHook.java
- src/main/java/io/gravitee/gateway/reactive/api/hook/InvokerMessageHook.java
- src/main/java/io/gravitee/gateway/reactive/api/hook/MessageHook.java
- src/main/java/io/gravitee/gateway/reactive/api/hook/PolicyMessageHook.java
- src/main/java/io/gravitee/gateway/reactive/api/message/DefaultMessage.java
- src/main/java/io/gravitee/gateway/reactive/api/message/Message.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/Tracer.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/message/TracingMessage.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/message/TracingMessageAttribute.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/message/TracingMessageMessagingSystem.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/message/TracingMessageOperationType.java
https://gravitee.atlassian.net/browse/ARCHI-401
To be defined
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-hnwlztrlnj.chromatic.com)
---
- use it directly by updating your project with version: `3.9.0-archi-401-opentelemetry-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-archi-401-opentelemetry-SNAPSHOT/gravitee-gateway-api-3.9.0-archi-401-opentelemetry-SNAPSHOT.zip)
> feat: add OpenTelemetry feature on Async API

- pom.xml
> fix: bump gravitee node version

- .circleci/config.yml
- src/main/java/io/gravitee/gateway/reactive/api/message/kafka/KafkaMessage.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-7304
> fix: prefer use Buffer instead of Object for recordHeaders

- pom.xml
- src/main/java/io/gravitee/gateway/reactive/api/tracing/Tracer.java
- src/main/java/io/gravitee/gateway/reactive/api/tracing/message/TracingMessage.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-431
---
- use it directly by updating your project with version: `3.9.0-archi-431-handle-context-propagation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-archi-431-handle-context-propagation-SNAPSHOT/gravitee-gateway-api-3.9.0-archi-431-handle-context-propagation-SNAPSHOT.zip)
> feat: allow to inject message tracing context to any carrier

- src/main/java/io/gravitee/gateway/reactive/api/message/kafka/KafkaMessage.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-7304
---
- use it directly by updating your project with version: `3.9.0-APIM-7304-header-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-APIM-7304-header-SNAPSHOT/gravitee-gateway-api-3.9.0-APIM-7304-header-SNAPSHOT.zip)
> feat: add putRecordHeader & removeRecordHeader to manage kafka header

- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/BaseEndpointConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/BaseEndpointConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/HttpEndpointConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/TcpEndpointConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/async/HttpEndpointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/endpoint/sync/HttpEndpointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/BaseEntrypointConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/EntrypointConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/TcpEntrypointConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/async/HttpEntrypointAsyncConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/async/HttpEntrypointAsyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/sync/EntrypointSyncConnector.java
- src/main/java/io/gravitee/gateway/reactive/api/connector/entrypoint/sync/HttpEntrypointSyncConnectorFactory.java
- src/main/java/io/gravitee/gateway/reactive/api/context/ExecutionContext.java
- src/main/java/io/gravitee/gateway/reactive/api/context/tcp/TcpRequest.java
- src/main/java/io/gravitee/gateway/reactive/api/context/tcp/TcpResponse.java
- src/main/java/io/gravitee/gateway/reactive/api/invoker/BaseInvoker.java
- src/main/java/io/gravitee/gateway/reactive/api/invoker/TcpInvoker.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7417
---
- use it directly by updating your project with version: `3.9.0-apim-7417-refactor-connectors-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.9.0-apim-7417-refactor-connectors-SNAPSHOT/gravitee-gateway-api-3.9.0-apim-7417-refactor-connectors-SNAPSHOT.zip)
> refactor: specialize entrypoints and endpoints for Http or Tcp contexts

- src/main/java/io/gravitee/gateway/api/service/Subscription.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-5979
Add applicationName field in Subscription object
---
- use it directly by updating your project with version: `3.11.0-apim-5979-subscription-application-name-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gateway/gravitee-gateway-api/3.11.0-apim-5979-subscription-application-name-SNAPSHOT/gravitee-gateway-api-3.11.0-apim-5979-subscription-application-name-SNAPSHOT.zip)
> feat: include applicationName in subscription
